separator = "|"
unique = false

[app_names]
# Terminals
xterm = "\uf120"
uxterm = "\uf120"
gnome-terminal = "\uf120"
alacritty = "\uf120"
termite = "\uf120"
lxterminal = "\uf120"

# Browsers
firefox = "\uf269"
google-chrome = "\uf268"
chromium = "\uf268"
naver-whale = "\uf0ac"
qutebrowser = "\uf0ac"

# File managers
nautilus = "\uf07c"
thunar = "\uf07c"

# Text editors
leafpad = "\uf044"
gedit = "\uf044"
mousepad = "\uf044"
joplin = "\uf044"

# Office
libreoffice-startcenter = "\uf1c2"
libreoffice-writer = "\uf1c2"
libreoffice-draw = "\uf61f"
libreoffice-calc = "\uf1c3"

# Documents
evince = "\uf1c1"

# Image viewers
sxiv = "\uf03e"
ristretto = "\uf03e"

# Media
vlc = "\uf04b"

# Graphics
gimp = "\uf53f"
pinta = "\uf53f"

# Email
thunderbird = "\uf0e0"

# Code editors
code = "\uf121"
"dev.zed.zed" = "\uf121"

# Cloud
nextcloud = "\uf0c2"

# Security
keepassxc = "\uf084"

# System
nm-connection-editor = "\uf6ff"
blueman-manager = "\uf293"
